import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

import {NextUIProvider} from "@nextui-org/react";

import Header from "@/components/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="purple-dark text-foreground bg-background">
      <body className={inter.className}>
        <NextUIProvider>
          <Header />
          <main className="my-bg">
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
